export const authActions = {
  //Logout
  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",

  //Login Actions
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_INVALID: "LOGIN_INVALID",

  NOTES_LISTING: "NOTES_LISTING",
  NOTES_LISTING_SUCCESS: "NOTES_LISTING_SUCCESS",
  NOTES_LISTING_ERROR: "NOTES_LISTING_ERROR",

  REGISTER_USER: "REGISTER_USER",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR",

};
