export const clientActionTypes = {
    CREATE_CLIENT : "CREATE_CLIENT",

    GET_ALL_CLIENTS : "GET_ALL_CLIENTS",
    GET_ALL_CLIENTS_SUCCESS: "GET_ALL_CLIENTS_SUCCESS",
    GET_ALL_CLIENTS_ERROR: "GET_ALL_CLIENTS_ERROR",

    GET_CLIENT_DETAILS : "GET_CLIENT_DETAILS",
    GET_CLIENT_DETAILS_SUCCESS: "GET_CLIENT_DETAILS_SUCCESS",
    GET_CLIENT_DETAILS_ERROR: "GET_CLIENT_DETAILS_ERROR",

    CLEAR_CLIENT_DETAILS : "CLEAR_CLIENT_DETAILS" 
}